# Generated by Django 6.0.7 on 2026-07-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('logo_path', models.ImageField(upload_to='static/course_icons')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=256)),
                ('major', models.CharField(max_length=256)),
                ('year', models.CharField(max_length=9)),
                ('semester', models.CharField(max_length=30)),
                ('establishment', models.CharField(max_length=256)),
                ('teacher', models.CharField(max_length=256)),
                ('paper_path', models.FileField(blank=True, null=True, upload_to='%y/%m/%d')),
            ],
        ),
    ]
