# Generated by Django 6.0.7 on 2026-08-01 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('logo_path', models.FileField(upload_to='course_icons')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=256)),
                ('year', models.CharField(max_length=9)),
                ('semester', models.CharField(max_length=30)),
                ('establishment', models.CharField(max_length=256)),
                ('teacher', models.CharField(max_length=256)),
                ('paper_path', models.FileField(blank=True, null=True, upload_to='papers/%y/%m/%d')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='pages.course')),
            ],
        ),
    ]
