# Generated by Django 6.0.7 on 2026-07-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='logo_path',
            field=models.FileField(upload_to='static/course_icons'),
        ),
    ]
