# Generated by Django 6.0.7 on 2026-08-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='cycle',
            field=models.CharField(choices=[('license', 'License'), ('master', 'Master'), ('engineer', 'Engineer')], default='engineer', max_length=20),
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('exam', 'Exam'), ('td', 'TD'), ('tp', 'TP'), ('quiz', 'Quiz')], default='exam', max_length=20),
        ),
    ]
