# Generated by Django 6.0.7 on 2026-07-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_course_logo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='logo_path',
            field=models.FileField(upload_to='course_icons'),
        ),
    ]
