# Generated by Django 6.0.7 on 2026-08-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_paper_cycle_paper_paper_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='logo_path',
            field=models.ImageField(upload_to='course_icons'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='establishment',
            field=models.CharField(default='unknown', max_length=256),
        ),
        migrations.AlterField(
            model_name='paper',
            name='major',
            field=models.CharField(default='unknown', max_length=256),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('exam', 'Exam'), ('mid-term', 'Mid-term')], default='exam', max_length=20),
        ),
        migrations.AlterField(
            model_name='paper',
            name='semester',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='paper',
            name='teacher',
            field=models.CharField(default='unknown', max_length=256),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.CharField(default='unknown', max_length=9),
        ),
    ]
