# Generated by Django 6.0.7 on 2026-08-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_donation_alter_course_logo_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='logo_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
