# Generated by Django 6.0.7 on 2026-07-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_course_logo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_path',
            field=models.FileField(blank=True, null=True, upload_to='media/papers/%y/%m/%d'),
        ),
    ]
