# Generated by Django 6.0.7 on 2026-09-13 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_course_logo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('exam', 'Exam'), ('mid-term', 'Mid-term'), ('td', 'TD'), ('tp', 'TP')], default='exam', max_length=20),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='pages.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='Only used for TD / TP papers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='pages.chapter'),
        ),
    ]
